---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "demo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  method: kubernetes
  mount: {{ .Values.vault.authMount }}
  kubernetes:
    role: {{ .Values.vault.role }}
    serviceAccount: {{ include "demo-app.fullname" . }}
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "demo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ trimPrefix "secret/data/" .Values.vault.secretPath }}
  destination:
    name: {{ .Values.vault.secretDestination }}
    create: true
  refreshAfter: 60s
  vaultAuthRef: {{ include "demo-app.fullname" . }}
